# Generated by Django 4.1.5 on 2023-01-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_personal_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other'), (4, 'Prefer Not Say')]),
        ),
    ]
