# Generated by Django 4.1.5 on 2023-01-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_alter_personal_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='created_user',
        ),
    ]
